import {vehicles, faqs} from './config.mjs';

export const guides = [
  {slug:'alirken-nelere-dikkat-edilmeli', title:'Elektrikli yan basamak alırken nelere dikkat edilmeli?', description:'Teklifleri aynı kapsamda karşılaştırın: araç kiti, motor, montaj, teknik belge ve servis.', sections:[['Önce araç uyumluluğu','Marka ve model tek başına yeterli değildir. Model yılı, kasa nesli, donanım ve mevcut gövde altı aksesuarları birlikte kontrol edilmelidir. Satıcıdan tam aracınız için kit kodunu ve uyumluluk teyidini isteyin.'],['Teknik bilgiyi belgeyle karşılaştırın','Taşıma kapasitesi, motor ve kontrol ünitesi, su ve toz koruma sınıfı, sıkışma algılama özelliği ve bakım gereksinimi ürüne göre değişir. Sözlü vaat yerine üreticinin teknik dokümanını isteyin.'],['Toplam maliyeti görün','Ürün, montaj, KDV, kargo ve ilave bağlantı işlemlerini ayrı sorun. Düşük ürün fiyatı ile montaj dahil fiyatı doğrudan karşılaştırmayın.'],['Satış sonrası desteği sorun','Garanti süresi kadar kapsamı da önemlidir. Motor, mekanizma ve işçilik için kapsamı; arıza halinde başvuracağınız işletmeyi ve yedek parça tedarik yöntemini öğrenin.']]},
  {slug:'sabit-mi-elektrikli-mi', title:'Sabit yan basamak mı, elektrikli yan basamak mı?', description:'Kullanım, görünüm ve bakım beklentilerine göre iki sistemi karşılaştırın.', sections:[['Kullanım farkı','Sabit basamak sürekli dışarıda durur. Elektrikli sistem, kapı sinyaliyle açılıp kullanılmadığında gövde altına çekilir. Her iki sistemde de basma yüzeyi ve araç yüksekliği değerlendirilmelidir.'],['Bakım ve maliyet','Sabit sistemde motor veya elektronik kontrol ünitesi bulunmaz. Elektrikli sistemin hareketli parçaları ve elektronik bağlantısı vardır. Bakım sıklığı ve servis ihtiyacı üretici talimatlarına göre değerlendirilir.'],['Hangisini seçmeli?','İniş ve biniş kolaylığı, aracın kullanım şekli, bütçe ve görünüm beklentilerinizi birlikte ele alın. Seçimden önce montaj yöntemi ve araç uyumluluğu teyit edilmelidir.']]},
  {slug:'fiyati-ne-belirler', title:'Elektrikli yan basamak fiyatını ne belirler?', description:'Araç bağlantı kiti, mekanizma ve montaj kapsamının fiyat üzerindeki rolü.', sections:[['Araca özel kit','Bağlantı aparatları, basamak boyu, kabin tipi ve elektronik arayüz seçimi toplam maliyetin parçalarıdır. Aynı markanın farklı modelleri için aynı fiyat varsayılamaz.'],['Ürün ve mekanizma','Malzeme, motor, kontrol ünitesi, teknik kapasite ve üretici servis desteği farklı teklifler arasında değişebilir. Teknik özellikleri aynı belgeler üzerinden kıyaslayın.'],['Montaj kapsamı','Elektrik bağlantısı, bağlantı aparatları ve son kontroller montaj teklifinin kapsamına yazılmalıdır. KDV ve diğer masrafların dahil olup olmadığını ayrıca sorun.']]},
  {slug:'montaj-kontrol-listesi', title:'Elektrikli yan basamak montajı için kontrol listesi', description:'Randevu öncesinde ve teslim sırasında kontrol edilecek konular.', sections:[['Randevu öncesi','Tam araç modelini ve yılını paylaşın. Kit uyumu, stok, montaj yeri, işlem süresi, toplam tutar ve garanti kapsamını yazılı teyit edin.'],['Bağlantı yöntemini öğrenin','Kesme, delme veya kaynak yapılıp yapılmayacağını sorun. Elektrik bağlantısının yöntemi ve araç üreticisinin garanti koşulları uygulama öncesinde açıklığa kavuşturulmalıdır.'],['Teslim kontrolü','Tüm kapılarda açılma ve kapanma davranışını, basamağın sabitliğini, kablo korumasını ve varsa emniyet özelliklerinin üreticiye uygun çalışmasını uygulayıcıyla kontrol edin. Fatura ve garanti belgelerini alın.']]},
  {slug:'suv-ve-pick-up-secimi', title:'SUV ve pick-up için elektrikli basamak seçimi', description:'Kabin tipi, basamak uzunluğu ve kullanım şekline göre seçim.', sections:[['SUV araçlarda','Kapı konumu, basamağın ön ve arka yolculara erişimi, gövde altı bağlantı noktaları ve yerden yükseklik birlikte değerlendirilir. Yalnızca dış görünüşe bakarak kit seçmeyin.'],['Pick-up araçlarda','Tek veya çift kabin, kasa nesli ve varsa arazi aksesuarları montajı etkileyebilir. Kabin tipini tam belirtin ve basamak uzunluğunu doğrulatın.'],['Arazi kullanımı','Çamur, taş teması ve su koşulları için ürünün kullanım sınırlarını öğrenin. Elektrikli basamak bir gövde koruma veya kaya kızağı olarak kabul edilmemelidir.']]},
];

export const pages = [
  {path:'/', type:'home', title:'Elektrikli Yan Basamak Fiyatları ve Modelleri', description:'SUV ve pick-up aracınız için elektrikli yan basamak seçimini kolaylaştırın. Marka, model ve yılı seçerek uyumluluk kontrolü ve montaj dahil teklif hazırlayın.'},
  {path:'/araclar/', type:'vehicles', title:'Araçlara Göre Elektrikli Yan Basamak', description:'Chery, Jaecoo, BYD, Volkswagen ve Ford için model bazında uyumluluk kontrolü hazırlayın.'},
  {path:'/elektrikli-yan-basamak-fiyatlari/', type:'prices', title:'Elektrikli Yan Basamak Fiyatları', description:'Araç modeli, mekanizma ve montaj kapsamına göre elektrikli yan basamak fiyatını etkileyen unsurları öğrenin.'},
  {path:'/montaj/', type:'installation', title:'Elektrikli Yan Basamak Montajı', description:'Araç uyumluluğu, montaj yöntemi, elektrik bağlantısı ve teslim kontrolünü adım adım öğrenin.'},
  {path:'/uygulamalar/', type:'applications', title:'Elektrikli Yan Basamak Uygulamaları', description:'Gerçek montaj görsellerinde incelenmesi gereken ayrıntılar ve uygulama kontrol listesi.', noindex:true},
  {path:'/hakkimizda/', type:'about', title:'Hakkımızda', description:'ElektrikliYanBasamak.com ile araç bazında seçim, şeffaf teklif ve montaj kontrolü.', noindex:true},
  {path:'/iletisim/', type:'contact', title:'İletişim ve Teklif', description:'Aracınızın marka, model ve yılını seçerek uyumluluk, fiyat ve montaj için teklif mesajı hazırlayın.', noindex:true},
  {path:'/rehber/', type:'guides', title:'Elektrikli Yan Basamak Rehberi', description:'Satın alma, fiyat, sabit basamak karşılaştırması ve montaj hakkında karar rehberleri.'},
  {path:'/garanti-ve-montaj-kosullari/', type:'terms', title:'Garanti ve Montaj Koşulları', description:'Teklif öncesinde yazılı olarak istenmesi gereken garanti ve montaj bilgileri.', noindex:true},
  {path:'/gizlilik/', type:'privacy', title:'Gizlilik ve Veri Kullanımı', description:'Bu sitede teklif mesajı hazırlarken bilgilerin nasıl kullanıldığı.', noindex:true},
  ...[...new Set(vehicles.map(v=>v.brandSlug))].map(slug=>({path:`/${slug}/`, type:'brand', brand:vehicles.find(v=>v.brandSlug===slug).brand, brandSlug:slug, title:`${vehicles.find(v=>v.brandSlug===slug).brand} Elektrikli Yan Basamak`, description:'Modeliniz için uyumluluk kontrolünde gerekli bilgileri ve teklif seçeneklerini inceleyin.', noindex:true})),
  ...vehicles.map(v=>({path:v.path, type:'model', vehicle:v, title:`${v.brand} ${v.model} Elektrikli Yan Basamak`, description:`${v.brand} ${v.model} için model yılı, donanım ve bağlantı kontrolü ile fiyat ve montaj talebi hazırlayın.`, noindex:!v.verified})),
  ...guides.map(g=>({path:`/rehber/${g.slug}/`, type:'guide', guide:g, title:g.title, description:g.description})),
];

export const commonFaqs = faqs;
