import {site, vehicles, faqs} from './config.mjs';
import {guides} from './pages.mjs';

export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escapeHtml;
const arrow = '<span aria-hidden="true">↗</span>';
const button = (label='Aracını seç', extra='') => `<button class="button" data-quote ${extra}>${label} ${arrow}</button>`;
const sectionHeading = (kicker,title,copy='') => `<div class="section-heading"><div><p class="eyebrow">${kicker}</p><h2>${title}</h2></div>${copy?`<p>${copy}</p>`:''}</div>`;
const vehicleCard = v=>`<article class="vehicle-card"><div class="vehicle-card-top"><span class="tag">${e(v.body)}</span><span class="monogram" aria-hidden="true">${e(v.brand.slice(0,1))}</span></div><p>${e(v.brand)}</p><h3><a href="${v.path}">${e(v.model)}</a></h3><div class="card-bottom"><span>Uyumluluk kontrolü</span><a href="${v.path}" aria-label="${e(v.brand+' '+v.model)} detaylarını incele">${arrow}</a></div></article>`;
const modelGrid = (list=vehicles)=>`<div class="vehicle-grid">${list.map(vehicleCard).join('')}</div>`;
const faqBlock = (list=faqs)=>`<section class="section"><div class="container narrow">${sectionHeading('MERAK EDİLENLER','Karar vermeden önce.')}<div class="faq-list">${list.map(([q,a])=>`<details><summary>${e(q)}<span aria-hidden="true">+</span></summary><p>${e(a)}</p></details>`).join('')}</div></div></section>`;
const brandOptions = `<option value="">Marka seçin</option>${[...new Set(vehicles.map(v=>v.brand))].map(b=>`<option>${e(b)}</option>`).join('')}<option value="other">Diğer marka</option>`;
const years = `<option value="">Yıl seçin</option>${Array.from({length:37},(_,i)=>2026-i).map(y=>`<option>${y}</option>`).join('')}`;

export function finder(prefix='finder') {
return `<form class="finder" id="${prefix}" data-finder>
  <div class="finder-title"><span class="number">01</span><div><h2>Aracınızla başlayalım.</h2><p>Üç seçim. Aracınıza özel bir teklif talebi.</p></div></div>
  <div class="finder-fields"><label for="${prefix}-brand">Marka<select id="${prefix}-brand" name="brand" required>${brandOptions}</select></label><label for="${prefix}-model">Model<select id="${prefix}-model" name="model" required disabled><option value="">Önce marka seçin</option></select></label><label for="${prefix}-year">Model yılı<select id="${prefix}-year" name="year" required>${years}</select></label><button class="button" type="submit">Uyumluluğu kontrol et ${arrow}</button></div>
  <div class="other-fields" hidden><label>Marka / model<input name="otherVehicle" maxlength="100" placeholder="Örn. Toyota Hilux çift kabin"></label></div>
  <p class="micro">Uyumluluk, stok ve fiyat araç bilgilerinizle ayrıca teyit edilir.</p>
  <div class="finder-result" role="status" aria-live="polite" hidden></div>
  <noscript><p>Teklif mesajı hazırlamak için JavaScript’i etkinleştirin. <a href="/iletisim/">İletişim bilgilerini inceleyin.</a></p></noscript>
</form>`;
}

const cta = ()=>`<section class="section"><div class="container"><div class="cta-panel"><div><p class="eyebrow">SIRADAKİ ADIM SİZİN</p><h2>Aracınız belli.<br>Şimdi doğru sistemi bulalım.</h2><p>Marka, model ve yılı paylaşın. Uyumluluk, fiyat ve montaj kapsamını tek mesajda sorun.</p></div>${button('Teklif mesajı hazırla')}</div></div></section>`;

function home() {
return `<section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span> SUV & PICK-UP İÇİN</p><h1><span class="hero-topic">Elektrikli yan basamak.</span>Aracınıza bir<br><em>adım</em> daha yakın.</h1><p class="hero-description">Elektrikli yan basamak seçeneklerini aracınıza göre inceleyin. Uyumluluğu kontrol ettirin, montaj dahil güncel teklif isteyin.</p><div class="hero-actions"><a class="button" href="#arac-sec">Aracıma uygun basamağı bul ${arrow}</a><a class="text-link" href="/elektrikli-yan-basamak-fiyatlari/">Fiyatları ne belirler? →</a></div><div class="hero-points"><span>Araca özel seçim</span><span>Montaj kapsamı kontrolü</span></div></div><div class="hero-visual"><div class="visual-label"><span>ELEKTRİKLİ YAN BASAMAK</span><span>01 / SİSTEM</span></div><img src="/vehicle.svg" width="900" height="520" alt="Açık elektrikli yan basamağı gösteren temsili SUV çizimi" fetchpriority="high"><div class="visual-caption"><span class="dot"></span> Kapı açılır. Basamak çıkar.<small>Temsili çizim · gerçek uygulama değildir</small></div></div></div></section>
<section class="finder-section" id="arac-sec"><div class="container">${finder()}</div></section>
<div class="brand-strip container"><span>ARAÇ BAZINDA İNCELEYİN</span>${[...new Set(vehicles.map(v=>v.brand))].map(b=>`<a href="/${vehicles.find(v=>v.brand===b).brandSlug}/">${e(b.toUpperCase())}</a>`).join('')}</div>
<section class="section"><div class="container">${sectionHeading('ARACINIZ İÇİN','Doğru seçim, doğru modelle başlar.','Popüler SUV ve pick-up modelleri için ürün seçimi ve uyumluluk kontrolü.')} ${modelGrid(vehicles.slice(0,4))}<div class="section-foot"><p>Listede olmak, kesin uyumluluk veya stok anlamına gelmez.</p><a class="text-link" href="/araclar/">Tüm araçları incele →</a></div></div></section>
<section class="section soft"><div class="container how-grid"><div><p class="eyebrow">GÜNLÜK KONFOR, AKILLI HAREKET</p><h2>İhtiyacınız olduğunda<br>bir adım öne çıkar.</h2><p class="muted">Elektrikli yan basamak, yüksek araçlara iniş ve binişi kolaylaştıran motorlu bir sistemdir. Kullanılmadığında gövde altına çekilir.</p><a class="text-link" href="/rehber/sabit-mi-elektrikli-mi/">Sabit ve elektrikli basamağı karşılaştır →</a></div><div class="steps"><article><span>01</span><div><h3>Kapı açılır</h3><p>Kontrol ünitesi kapı sinyalini algılar.</p></div></article><article><span>02</span><div><h3>Basamak dışarı çıkar</h3><p>Motorlu mekanizma basma yüzeyini erişilebilir konuma getirir.</p></div></article><article><span>03</span><div><h3>Gövde altına çekilir</h3><p>Kapı kapandığında sistem geri kapanır. Çalışma şekli ürüne göre değişir.</p></div></article></div></div></section>
<section class="section"><div class="container price-preview"><div><p class="eyebrow">ŞEFFAF TEKLİF</p><h2>“Kaça olur?” sorusuna<br>doğru kapsamla cevap.</h2><p class="muted">Fiyatı aracınız, ürün ve montaj yöntemi belirler. Teklifte tüm kalemleri görün, aynı kapsamı karşılaştırın.</p><a class="text-link" href="/elektrikli-yan-basamak-fiyatlari/">Fiyat rehberini incele →</a></div><div class="quote-checklist"><p>TEKLİFİNİZDE BULUNSUN</p>${['Aracınıza uygun ürün ve bağlantı kiti','Montaj ve ilave işlem kapsamı','KDV dahil toplam tutar','Stok, garanti ve randevu bilgisi'].map((s,i)=>`<div><span>0${i+1}</span>${s}<b aria-hidden="true">✓</b></div>`).join('')}${button('Aracıma özel teklif hazırlayayım')}</div></div></section>
<section class="section soft"><div class="container">${sectionHeading('MONTAJ ÖNCESİNDEN TESLİME','Her adımı netleştirin.')}<div class="three-grid">${[['01','Uyumluluğu teyit edin','Model yılı, donanım ve bağlantı noktaları beraber değerlendirilir.'],['02','Kapsamı öğrenin','Montaj yöntemi, elektrik bağlantısı ve süreyi yazılı olarak isteyin.'],['03','Birlikte kontrol edin','Açılma-kapanma, sabitlik ve teslim belgelerini uygulayıcıyla inceleyin.']].map(([n,t,p])=>`<article class="info-card"><span class="step-number">${n}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div><div class="section-foot"><a class="text-link" href="/montaj/">Montaj sürecini incele →</a></div></div></section>
${faqBlock(faqs.slice(0,5))}${cta()}`;
}

function intro(page) { return `<section class="page-intro container"><nav class="breadcrumbs" aria-label="İçerik yolu"><a href="/">Ana sayfa</a><span>/</span>${page.type==='model'?`<a href="/${page.vehicle.brandSlug}/">${e(page.vehicle.brand)}</a><span>/</span>`:page.type==='guide'?'<a href="/rehber/">Rehber</a><span>/</span>':''}<span aria-current="page">${e(page.type==='model'?page.vehicle.model:page.title)}</span></nav><p class="eyebrow">${page.type==='guide'?'KARAR REHBERİ':'ARACINIZ İÇİN DOĞRU ADIM'}</p><h1>${e(page.title)}</h1><p>${e(page.description)}</p></section>`; }
const prose = sections=>`<div class="prose">${sections.map(([h,p])=>`<section><h2>${e(h)}</h2><p>${e(p)}</p></section>`).join('')}</div>`;

function inner(page) {
let body='';
switch(page.type) {
 case 'vehicles': body=`${sectionHeading('MODEL SEÇİMİ','Aracınızı bulun.','Listede olmayan bir araç için de kontrol talebi hazırlayabilirsiniz.')}${modelGrid()}<div class="section-foot"><p>Uyumluluk bilgileri teknik kontrol sonrası teyit edilir.</p></div>${finder('catalog-finder')}`; break;
 case 'brand': body=`<div class="notice">Bu marka için model bazlı teknik ürün verileri henüz doğrulanmamıştır. Aşağıdaki sayfalar seçim ve kontrol talebi hazırlamak içindir.</div>${modelGrid(vehicles.filter(v=>v.brandSlug===page.brandSlug))}${finder('brand-finder')}`; break;
 case 'model': { const v=page.vehicle; body=`<div class="model-detail"><div class="model-image"><img src="/vehicle.svg" width="900" height="520" alt="Elektrikli yan basamak sisteminin temsili çizimi"><p>Temsili sistem çizimi. ${e(v.brand+' '+v.model)} uygulama fotoğrafı değildir.</p></div><div><span class="tag">Uyumluluk teyidi gerekli</span><h2>Modelinizi birlikte kontrol edelim.</h2><p>${e(v.note)}</p><dl class="specs">${[['Araç',`${v.brand} ${v.model}`],['Uyumlu yıllar','Teknik kontrol ile teyit edilir'],['Fiyat ve stok','Güncel teklif ile teyit edilir'],['Garanti / kapasite','Ürün belgesine göre belirlenir'],['Montaj yeri ve süresi','Teklifte belirtilmelidir']].map(([k,val])=>`<div><dt>${k}</dt><dd>${e(val)}</dd></div>`).join('')}</dl>${button('Bu araç için teklif hazırla',`data-brand="${e(v.brand)}" data-model="${e(v.model)}"`)}</div></div><div class="content-block">${prose([['Teklif için hangi bilgiler gerekli?',`${v.brand} ${v.model} aracınızın model yılını, donanımını ve montaj istediğiniz şehri belirtin. Mevcut basamak veya gövde altı aksesuarı varsa ekleyin. Araç seçimi tek başına uyumluluğu garanti etmez.`],['Uyumluluk nasıl doğrulanır?','Araca özel kit kodu, bağlantı noktaları ve elektronik bağlantı yöntemi teknik ekiple doğrulanmalıdır. Kapasite, garanti ve montaj süresi gibi özellikler teklif edilen ürüne göre yazılı belirtilmelidir.']])}</div>`; break; }
 case 'prices': body=`<div class="price-summary"><p class="eyebrow">KESİN FİYAT, ARACINIZA ÖZEL</p><h2>Ürün + montaj + KDV.<br>Hepsini birlikte sorun.</h2><p>Elektrikli yan basamak fiyatı; araç modeli, bağlantı kiti, motor ve mekanizma ile montaj kapsamına göre değişir. Doğrulanmış satış fiyatı olmadan bir başlangıç tutarı yayınlamıyoruz. Aracınıza özel güncel teklifi isteyin.</p>${button('Fiyat talebi hazırla')}</div><h2>Araçlara göre fiyat talebi</h2><div class="table-wrap"><table><caption>Model bazında elektrikli yan basamak teklif seçenekleri</caption><thead><tr><th scope="col">Araç</th><th scope="col">Uyumluluk</th><th scope="col">Fiyat</th></tr></thead><tbody>${vehicles.map(v=>`<tr><th scope="row"><a href="${v.path}">${e(v.brand+' '+v.model)}</a></th><td>Kontrol gerekli</td><td><button class="table-cta" data-quote data-brand="${e(v.brand)}" data-model="${e(v.model)}">Teklif hazırla ↗</button></td></tr>`).join('')}</tbody></table></div>${prose([['Fiyatı ne belirler?','Araca özel bağlantı aparatı, basamak boyu, motor ve kontrol ünitesi, malzeme, teknik kapasite ve montaj işlemleri maliyeti etkiler. Kargo ve ilave işlemler varsa bunların da toplam tutarda belirtilmesini isteyin.'],['Teklifleri nasıl karşılaştırmalı?','Yalnızca ürün fiyatı ile montaj dahil fiyatı karşılaştırmayın. Aynı teknik özellikler, aynı vergi ve montaj kapsamı, aynı garanti şartları üzerinden değerlendirin.']])}`;break;
 case 'installation': body=`<div class="three-grid">${[['01','Araç kontrolü','Marka, tam model, yıl, donanım ve mevcut aksesuarları paylaşın.'],['02','Ürün ve randevu','Kit uyumu, stok, montaj yöntemi, şehir, süre ve toplam tutarı yazılı teyit edin.'],['03','Uygulama ve teslim','Montaj sonrası tüm kapıları ve sabitliği birlikte kontrol edin. Belgelerinizi alın.']].map(([n,t,p])=>`<article class="info-card"><span class="step-number">${n}</span><h2>${t}</h2><p>${p}</p></article>`).join('')}</div>${prose([['Kesme, delme veya kaynak yapılıyor mu?','Bu sorunun cevabı araç ve montaj kitine göre değişir. İşlem başlamadan uygulayıcıdan bağlantı yöntemini yazılı olarak öğrenin. Tüm ürünler için işlemsiz montaj sözü verilmemelidir.'],['Elektrik bağlantısı ve araç garantisi','Kapı sinyalinin alınma şekli, kablo koruması ve kontrol ünitesi bağlantısı ürün dokümanıyla değerlendirilmelidir. Araç üreticisinin garanti koşullarını yetkili servisten teyit edin.'],['Montaj nerede yapılır?','Montaj lokasyonları ve randevu imkânı teklif aşamasında teyit edilmelidir. Doğrulanmış uygulayıcı bilgisi olmadan herhangi bir şehirde montaj hizmeti sunulduğu kabul edilmemelidir.']])}<a class="text-link" href="/rehber/montaj-kontrol-listesi/">Teslim kontrol listesini aç →</a>`;break;
 case 'applications':body=`<div class="empty-state"><span class="step-number">↗</span><h2>Gerçek uygulamalar için doğru kanıt.</h2><p>Doğrulanmış montaj fotoğrafı ve videosu henüz eklenmedi. Temsili çizimleri müşteri uygulaması olarak göstermiyoruz.</p></div>${prose([['Uygulama görsellerinde neye bakılmalı?','Aynı aracın açık ve kapalı basamak görüntüsü, yandan görünümü, bağlantı noktaları ve açılma videosunu isteyin. Araç modeli, yılı ve uygulayıcı bilgisi görsellerle eşleştirilmelidir.'],['Montaj kaydında bulunması gerekenler','Ürün ve kit kodu, araç yılı, montaj şehri, uygulama tarihi ve teknik sorumlu bilgisi kayıt altına alınmalıdır. Bir araçtaki montaj, diğer modeller için uyumluluk kanıtı değildir.']])}`;break;
 case 'guides':body=`<div class="guide-grid">${guides.map((g,i)=>`<article class="guide-card"><p class="eyebrow">REHBER / 0${i+1}</p><h2><a href="/rehber/${g.slug}/">${e(g.title)}</a></h2><p>${e(g.description)}</p><a class="text-link" href="/rehber/${g.slug}/">Rehberi oku →</a></article>`).join('')}</div>`;break;
 case 'guide':body=`<div class="article-layout"><article><p class="article-meta">Son içerik güncellemesi: 7 Ekim 2026 · Genel seçim rehberi</p>${prose(page.guide.sections)}<p class="notice">Teknik değerler, garanti ve uyumluluk teklif edilen ürünün belgeleriyle teyit edilmelidir.</p></article><aside class="article-aside"><p class="eyebrow">ARACINIZA ÖZEL</p><h2>Okudunuz.<br>Şimdi kontrol edin.</h2><p>Marka, model ve yılı seçerek teklif mesajınızı hazırlayın.</p>${button('Aracımı seçeyim')}<a class="text-link" href="/rehber/">Tüm rehberler →</a></aside></div>`;break;
 case 'contact':body=`${finder('contact-finder')}<div class="content-block">${site.whatsapp||site.phone||site.email?`<h2>Doğrudan iletişim</h2><div class="contact-links">${site.whatsapp?`<a class="button" href="https://wa.me/${e(site.whatsapp)}" target="_blank" rel="noopener noreferrer">WhatsApp ${arrow}</a>`:''}${site.phone?`<a href="tel:${e(site.phone.replace(/[^+0-9]/g,''))}">${e(site.phone)}</a>`:''}${site.email?`<a href="mailto:${e(site.email)}">${e(site.email)}</a>`:''}</div>`:'<h2>Teklif mesajınızı hazırlayın.</h2><p>Doğrudan iletişim kanalı henüz eklenmedi. Hazırladığınız mesajı kopyalayabilirsiniz. Bu adım bir teklif talebi göndermez ve randevu oluşturmaz.</p>'}${site.company?`<p>${e(site.company)}</p>`:''}${site.address?`<address>${e(site.address)}</address>`:''}</div>`;break;
 case 'about':body=prose([['Araç seçimiyle başlayan bir yol','ElektrikliYanBasamak.com, elektrikli yan basamak seçimini araç modeli üzerinden kolaylaştırmak için hazırlanmıştır. Araç seçimi, fiyat kapsamı, montaj yöntemi ve teknik belgeler aynı karar akışında ele alınır.'],['Bilgiyi teyit ederek ilerleyin','Ürün bulunabilirliği, model yılı uyumluluğu, kapasite ve garanti ancak doğrulanmış ürün bilgileriyle belirtilir. İşletme kimliği ve montaj uygulayıcısı bilgileri tamamlandığında bu sayfada yayınlanacaktır.']]);break;
 case 'terms':body=prose([['Garanti bilgisi','Ürünün garanti süresi ve kapsamı üretici ve satıcı belgelerine bağlıdır. Motor, mekanizma, elektronik kontrol ünitesi ve montaj işçiliği için kapsamı ayrı isteyin. Bu sayfa bir garanti taahhüdü vermez.'],['Montaj kapsamı','Araç uyumluluğu, montaj yeri, süre, bağlantı yöntemi ve ilave işlemler teklif öncesinde yazılı belirtilmelidir. Randevu, uygulayıcı tarafından teyit edildiğinde kesinleşir.'],['Satın alma ve iade','Bu sitede ödeme alınmaz ve çevrim içi sipariş oluşturulmaz. Satın alma öncesinde satıcı kimliği, ürün bilgileri, sözleşme ve geçerli iade şartları satıcıdan alınmalıdır.']]);break;
 case 'privacy':body=prose([['Mesajınız cihazınızda hazırlanır','Araç seçiciye yazdığınız araç bilgileri ve ek notlar, teklif metni hazırlamak için tarayıcınızda kullanılır. Bu site bir talep veritabanına bilgi kaydetmez. Mesajı kopyalamak bir başvuru veya gönderim değildir.'],['WhatsApp’a geçiş','WhatsApp bağlantısı etkinleştirildiğinde, seçtiğiniz araç bilgileri ve yazdığınız notlar hazırlanan bağlantıya eklenir. Gönderim WhatsApp içinde sizin işleminizle gerçekleşir. WhatsApp’ın kendi veri işleme koşulları geçerlidir.'],['Analitik ve barındırma','Bu sürümde analitik, reklam izleyicisi veya çerez tabanlı ölçüm kullanılmaz. Barındırma sağlayıcısı teknik erişim kayıtları tutabilir. Veri sorumlusu ve iletişim bilgileri tamamlanmadan kişisel veri toplayan bir form etkinleştirilmemelidir.']]);break;
}
return intro(page)+`<section class="section inner-content"><div class="container">${body}</div></section>`+(['prices','model','installation'].includes(page.type)?faqBlock(page.type==='model'?faqs.slice(1,5):faqs.slice(1,7)):'')+(!['contact','privacy','terms'].includes(page.type)?cta():'');
}

function schema(page) {
const url=site.url+page.path;
const graph=[{'@type':'WebSite','@id':site.url+'/#website',url:site.url,name:site.name,inLanguage:'tr-TR'},{'@type':'WebPage','@id':url+'#webpage',url,name:page.title,description:page.description,isPartOf:{'@id':site.url+'/#website'},inLanguage:'tr-TR'}];
if(page.path!=='/') {
 const items=[{name:'Ana sayfa',item:site.url+'/'}];
 if(page.type==='model') items.push({name:page.vehicle.brand,item:site.url+'/'+page.vehicle.brandSlug+'/'});
 if(page.type==='guide') items.push({name:'Rehber',item:site.url+'/rehber/'});
 items.push({name:page.title,item:url});
 graph.push({'@type':'BreadcrumbList',itemListElement:items.map((v,i)=>({'@type':'ListItem',position:i+1,...v}))});
}
const displayed=page.type==='home'?faqs.slice(0,5):page.type==='model'?faqs.slice(1,5):['prices','installation'].includes(page.type)?faqs.slice(1,7):[];
if(displayed.length) graph.push({'@type':'FAQPage',mainEntity:displayed.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))});
if(page.type==='guide') graph.push({'@type':'Article',headline:page.title,description:page.description,inLanguage:'tr-TR',dateModified:site.updated,mainEntityOfPage:url});
// No Product, Offer, LocalBusiness, reviews or expert attribution without verified data.
return JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c');
}

function dialog() {
return `<dialog id="quote-dialog" aria-labelledby="quote-title"><button class="dialog-close" type="button" aria-label="Teklif penceresini kapat">×</button><p class="eyebrow">ARACINIZA ÖZEL TEKLİF</p><h2 id="quote-title">Bir mesajla netleştirin.</h2><p>Uyumluluk, fiyat ve montaj bilgisi için mesajınızı hazırlayın.</p><form id="quote-form"><div class="dialog-fields"><label for="quote-brand">Marka<select id="quote-brand" name="brand" required>${brandOptions}</select></label><label for="quote-model">Model<select id="quote-model" name="model" required disabled><option value="">Önce marka seçin</option></select></label><label for="quote-year">Model yılı<select id="quote-year" name="year" required>${years}</select></label><label for="quote-city">Montaj şehri <span>(isteğe bağlı)</span><input id="quote-city" name="city" maxlength="50" autocomplete="address-level2" placeholder="Örn. Antalya"></label></div><div class="other-fields" hidden><label for="quote-other">Marka / model<input id="quote-other" name="otherVehicle" maxlength="100" placeholder="Aracınızın tam modeli"></label></div><label for="quote-detail">Ek bilgi <span>(isteğe bağlı)</span><input id="quote-detail" name="detail" maxlength="300" placeholder="Donanım, kabin tipi veya mevcut aksesuar"></label><button class="button full" type="submit">Teklif mesajımı hazırla ${arrow}</button><p class="micro">Bu adım bilgi göndermez. <a href="/gizlilik/">Veri kullanımı</a></p></form><div id="quote-output" hidden><label for="quote-message">Hazır mesajınız<textarea id="quote-message" rows="7" readonly></textarea></label><div class="output-actions"><button class="button" type="button" id="copy-message">Mesajı kopyala</button>${site.whatsapp?`<a class="button secondary" id="whatsapp-send" target="_blank" rel="noopener noreferrer">WhatsApp’ta aç ↗</a>`:''}</div><p id="copy-status" role="status" aria-live="polite"></p><p class="micro">${site.whatsapp?'Mesajı WhatsApp içinde siz gönderirsiniz.':'İletişim kanalı henüz eklenmedi. Mesajınız gönderilmedi.'}</p><button class="text-button" id="edit-message" type="button">Araç bilgilerini düzenle</button></div></dialog>`;
}

export function render(page) {
const title=`${page.title} | ${site.name}`;
const noindex=!site.allowIndexing||page.noindex;
return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(page.description)}"><meta name="robots" content="${noindex?'noindex, follow':'index, follow'}"><meta name="theme-color" content="#12221c"><link rel="canonical" href="${e(site.url+page.path)}"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><meta property="og:type" content="${page.type==='guide'?'article':'website'}"><meta property="og:locale" content="tr_TR"><meta property="og:site_name" content="${site.name}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(page.description)}"><meta property="og:url" content="${e(site.url+page.path)}"><script type="application/ld+json">${schema(page)}</script><script src="/app.js" type="module"></script></head><body><a class="skip-link" href="#main">İçeriğe geç</a><header class="site-header"><div class="container header-inner"><a class="logo" href="/" aria-label="ElektrikliYanBasamak.com ana sayfa"><span class="logo-symbol" aria-hidden="true">ϟ</span><span>Elektrikli<span class="logo-bottom">YanBasamak<span>.com</span></span></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menü <span aria-hidden="true">☰</span></button><nav id="main-nav" aria-label="Ana menü">${[['/araclar/','Araçlar'],['/elektrikli-yan-basamak-fiyatlari/','Fiyatlar'],['/montaj/','Montaj'],['/uygulamalar/','Uygulamalar'],['/rehber/','Rehber'],['/iletisim/','İletişim']].map(([href,text])=>`<a href="${href}"${page.path===href?' aria-current="page"':''}>${text}</a>`).join('')}</nav><div class="header-action">${button('Aracını seç')}</div></div></header><main id="main">${page.type==='home'?home():inner(page)}</main><footer><div class="container"><div class="footer-top"><div><a class="footer-brand" href="/">ElektrikliYanBasamak.com</a><p>Aracınıza uygun sistemi seçin.<br>Her adımı net bilgiyle atın.</p></div><div><h2>Keşfedin</h2><a href="/araclar/">Araçlar</a><a href="/elektrikli-yan-basamak-fiyatlari/">Fiyat rehberi</a><a href="/montaj/">Montaj</a><a href="/rehber/">Karar rehberleri</a></div><div><h2>Bilgi</h2><a href="/hakkimizda/">Hakkımızda</a><a href="/iletisim/">İletişim</a><a href="/garanti-ve-montaj-kosullari/">Garanti ve montaj koşulları</a><a href="/gizlilik/">Gizlilik ve veri kullanımı</a></div></div><div class="footer-bottom"><span>© 2026 ElektrikliYanBasamak.com</span><span>Uyumluluk ve ticari koşullar teklif aşamasında teyit edilir.</span></div></div></footer><div class="mobile-sticky"><a href="${page.type==='home'?'#arac-sec':'/araclar/'}">Aracını seç</a><button data-quote>${site.whatsapp?'WhatsApp teklifi':'Teklif hazırla'} ${arrow}</button></div>${dialog()}</body></html>`;
}
